# imagen base
FROM python:3.12-slim

# carpeta de trabajo
WORKDIR /EXAMEN_2DO

# copiar dependencias
COPY requirements.txt .

# instalar dependencias
RUN pip install --no-cache-dir -r requirements.txt

# copiar API
COPY ./app ./app

# puerto de la API
EXPOSE 5001

# ejecutar FastAPI
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5002", "--reload"]


