version: "3.9"

services:
  api:
    build: .
    container_name: EXAMEN_2DO_API
    ports:
      - "5002:5002"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 5002
